/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cypher */

#ifndef _Included_Cypher
#define _Included_Cypher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Cypher
 * Method:    desKeySetUp
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Cypher_desKeySetUp
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Cypher
 * Method:    desEncryption
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_Cypher_desEncryption
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     Cypher
 * Method:    desDecryption
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_Cypher_desDecryption
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     Cypher
 * Method:    aesKeySetUp
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Cypher_aesKeySetUp
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Cypher
 * Method:    aesEncryption
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_Cypher_aesEncryption
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     Cypher
 * Method:    aesDecryption
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_Cypher_aesDecryption
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     Cypher
 * Method:    rc4KeySetup
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Cypher_rc4KeySetup
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Cypher
 * Method:    rc4GenKey
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_Cypher_rc4GenKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
