/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE WITHOUT COPYING TO YOUR SRC DIRECTORY.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */

/* C++ header file for class com.tencent.audioeffect.effect.impl.KalaMix */
#pragma once

#include <jni.h>

namespace  KalaMix {

//DO NOT modify
static constexpr auto FULL_CLASS_NAME = "com/tencent/audioeffect/effect/impl/KalaMix";



/*
 * Class:     com_tencent_audioeffect_effect_impl_KalaMix
 * Method:    private static long create(int sampleRate, int bgmChannelCount, int vocalChannelCount)
 * Signature: (III)J
 */
jlong create(JNIEnv *env, jclass clazz, jint sampleRate, jint bgmChannelCount, jint vocalChannelCount);


/*
 * Class:     com_tencent_audioeffect_effect_impl_KalaMix
 * Method:    private static int process(long handel, byte[] bgm, int bgmSize, byte[] vocal, int vocalSize, byte[] out, int outSize)
 * Signature: (J[BI[BI[BI)I
 */
jint process(JNIEnv *env, jclass clazz, jlong handel, jbyteArray bgm, jint bgmSize, jbyteArray vocal, jint vocalSize, jbyteArray out, jint outSize);


/*
 * Class:     com_tencent_audioeffect_effect_impl_KalaMix
 * Method:    private void release(long handel)
 * Signature: (J)V
 */
void release(JNIEnv *env, jobject thiz, jlong handel);




/**
 * register Native functions
 * @returns success or not
 */
bool registerNativeFunctions(JNIEnv *env);

} //endof namespace KalaMix
