/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE WITHOUT COPYING TO YOUR SRC DIRECTORY.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */

/* C++ header file for class com.young.jennysampleapp.ComputeIntensiveClass */
#pragma once

#include <jni.h>

namespace  KalaVolumeScaler {

//DO NOT modify
static constexpr auto FULL_CLASS_NAME = "com/tencent/audioeffect/effect/impl/KalaVolumeScaler";



/*
 * Class:     com_tencent_audioeffect_effect_impl_KalaVolumeScaler
 * Method:    private static long create(int sampleRate, int channelCount)
 * Signature: (II)J
 */
jlong create(JNIEnv *env, jclass clazz, jint sampleRate, jint channelCount);


/*
 * Class:     com_tencent_audioeffect_effect_impl_KalaVolumeScaler
 * Method:    private static int setScaleFactor(long nativeHandel, int factor)
 * Signature: (JI)I
 */
jint setScaleFactor(JNIEnv *env, jclass clazz, jlong nativeHandel, jint factor);


/*
 * Class:     com_tencent_audioeffect_effect_impl_KalaVolumeScaler
 * Method:    private static int process(long nativeHandel, byte[] inOutBuffer, int size)
 * Signature: (J[BI)I
 */
jint process(JNIEnv *env, jclass clazz, jlong nativeHandel, jbyteArray inOutBuffer, jint size);


/*
 * Class:     com_tencent_audioeffect_effect_impl_KalaVolumeScaler
 * Method:    private static void release(long nativeHandel)
 * Signature: (J)V
 */
void release(JNIEnv *env, jclass clazz, jlong nativeHandel);




/**
 * register Native functions
 * @returns success or not
 */
bool registerNativeFunctions(JNIEnv *env);

} //endof namespace KalaVolumeScaler
