/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE WITHOUT COPYING TO YOUR SRC DIRECTORY.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */

/* C++ header file for class com.tencent.component.media.effect.VoiceChangerWrapper */
#pragma once

#include <jni.h>

namespace  VoiceChangerWrapper {

//DO NOT modify
static constexpr auto FULL_CLASS_NAME = "com/tencent/component/media/effect/VoiceChangerWrapper";



/*
 * Class:     com_tencent_component_media_effect_VoiceChangerWrapper
 * Method:    private static long nativeCreate()
 * Signature: ()J
 */
jlong nativeCreate(JNIEnv *env, jclass clazz);


/*
 * Class:     com_tencent_component_media_effect_VoiceChangerWrapper
 * Method:    private void setParam(long nativeHandel, int sampleRate, int channel, float tempoDelta, float pitchDelta, int voiceKind, int environment)
 * Signature: (JIIFFII)V
 */
void setParam(JNIEnv *env, jobject thiz, jlong nativeHandel, jint sampleRate, jint channel, jfloat tempoDelta, jfloat pitchDelta, jint voiceKind, jint environment);


/*
 * Class:     com_tencent_component_media_effect_VoiceChangerWrapper
 * Method:    private int nativeProcess(long nativeHandel, byte[] inData, int inDatasize, byte[] outData, int outDatasize)
 * Signature: (J[BI[BI)I
 */
jint nativeProcess(JNIEnv *env, jobject thiz, jlong nativeHandel, jbyteArray inData, jint inDataSize, jbyteArray outData, jint outDatasize);


/*
 * Class:     com_tencent_component_media_effect_VoiceChangerWrapper
 * Method:    private void nativeRelease(long nativeHandel)
 * Signature: (J)V
 */
void nativeRelease(JNIEnv *env, jobject thiz, jlong nativeHandel);




/**
 * register Native functions
 * @returns success or not
 */
bool registerNativeFunctions(JNIEnv *env);

} //endof namespace VoiceChangerWrapper
