#include "CHelper.h"

static const ENVIRONMENT wah_2012_11[30] = {
	/*01*/WEEKDAY_GOOD_WEATHER, WEEKDAY_GOOD_WEATHER,
	WEEKENDS_BAD_WHETHER, WEEKENDS_BAD_WHETHER,
	WEEKDAY_BAD_WHETHER, WEEKDAY_GOOD_WEATHER,
	WEEKDAY_GOOD_WEATHER, WEEKDAY_GOOD_WEATHER,
	WEEKDAY_GOOD_WEATHER, WEEKENDS_BAD_WHETHER,
	WEEKENDS_GOOD_WEATHER, WEEKDAY_GOOD_WEATHER,
	WEEKDAY_GOOD_WEATHER, WEEKDAY_GOOD_WEATHER,
	WEEKDAY_GOOD_WEATHER, WEEKDAY_BAD_WHETHER,
	WEEKENDS_GOOD_WEATHER, WEEKENDS_GOOD_WEATHER,
	WEEKDAY_GOOD_WEATHER, WEEKDAY_GOOD_WEATHER,
	WEEKDAY_GOOD_WEATHER, WEEKDAY_GOOD_WEATHER,
	WEEKDAY_GOOD_WEATHER, WEEKENDS_GOOD_WEATHER,
	WEEKENDS_GOOD_WEATHER, WEEKDAY_GOOD_WEATHER,
	WEEKDAY_GOOD_WEATHER, WEEKDAY_GOOD_WEATHER,
	WEEKDAY_GOOD_WEATHER, WEEKDAY_GOOD_WEATHER,
};

RoadID_t CHelper::getRoadID(GPSCoor_t longitude, GPSCoor_t latitude) {

	return 0;
}

ENVIRONMENT CHelper::getWeatherAndHoliday(const Date_t date) {

	if(date.year == 2012 &&
			date.month == 11 &&
			date.day >= 1 &&
			date.day <= 30) {
		return static_cast<ENVIRONMENT>(wah_2012_11[date.day - 1]);
	}
	return WEEKDAY_GOOD_WEATHER;
}
